name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: macos-15-intel
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Run flake checks
        run: nix flake check
